export const SCREENS = [
  { name: 'foundations', title: 'Foundations', group: 'Foundations', description: 'Colors, typography, spacing, radius, targets, states' },
  { name: 'tappable', title: 'Tappable', group: 'Core', description: 'Pressed state, disabled, 44pt touch target' },
  { name: 'overlay', title: 'Portal & Overlay', group: 'Core', description: 'Backdrop rendered in the root portal host' },
  { name: 'typography', title: 'Text & Title', group: 'Typography', description: 'Variants, colors, weights, nesting' },
  { name: 'icon', title: 'Icon', group: 'Atoms', description: 'Registry, sizes, colors, accessibility' },
  { name: 'icon-button', title: 'IconButton', group: 'Atoms', description: 'Variants, sizes, shapes, toggles' },
  { name: 'floating-button', title: 'FloatingButton', group: 'Atoms', description: 'Placement, extended, visibility' },
  { name: 'button', title: 'Button', group: 'Atoms', description: 'Variants, sizes, loading, disabled, icons' },
  { name: 'switch', title: 'Switch', group: 'Atoms', description: 'Controlled, uncontrolled, sizes, disabled' },
  { name: 'checkbox', title: 'Checkbox & Radio', group: 'Atoms', description: 'Indeterminate, error, groups, custom rows' },
  { name: 'segmented-control', title: 'SegmentedControl & Slider', group: 'Atoms', description: 'Sliding indicator, drag, range, steps' },
  { name: 'input', title: 'Input & TextArea', group: 'Atoms', description: 'Label, helper, error, affixes, auto-grow, count' },
  { name: 'input-group', title: 'InputGroup', group: 'Atoms', description: 'Addons, inline button, shared focus border' },
  { name: 'input-otp', title: 'InputOTP', group: 'Atoms', description: 'Paste, autofill, groups, error shake, PIN' },
  { name: 'card', title: 'Card, Item & Accordion', group: 'Atoms', description: 'Card parts, list rows, options, sections, button groups' },
  { name: 'badge', title: 'Badge, Avatar & Chip', group: 'Atoms', description: 'Counters, initials, status, filters, tags, separators' },
  { name: 'alert', title: 'Feedback', group: 'Atoms', description: 'Spinner, skeleton, alert, empty states' },
  { name: 'calendar', title: 'Calendar & Carousel', group: 'Atoms', description: 'Single and range selection, swipe, autoplay, dots' },
  { name: 'toast', title: 'Toast & Snackbar', group: 'Atoms', description: 'Stack, promise, swipe, undo, replace' },
  { name: 'dialog', title: 'Dialog & Menu', group: 'Atoms', description: 'Confirmation, async action, context menu, submenu' },
  { name: 'bottom-sheet', title: 'BottomSheet', group: 'Atoms', description: 'Snap points, gestures, scroll, footer, detached' },
] as const;
