// Generated by scripts/theme-css.ts from the tokens. Don't edit.
/* global __dirname */
const fs = require("fs");
const path = require("path");

const preset = {
	theme: {
		extend: {
			colors: {
				background: {
					DEFAULT: "var(--color-background)",
					subtle: "var(--color-background-subtle)",
					elevated: "var(--color-background-elevated)",
					inverse: "var(--color-background-inverse)",
				},
				content: {
					DEFAULT: "var(--color-content)",
					muted: "var(--color-content-muted)",
					subtle: "var(--color-content-subtle)",
					disabled: "var(--color-content-disabled)",
					inverse: "var(--color-content-inverse)",
					link: "var(--color-content-link)",
				},
				border: {
					DEFAULT: "var(--color-border)",
					subtle: "var(--color-border-subtle)",
					strong: "var(--color-border-strong)",
					focus: "var(--color-border-focus)",
				},
				primary: {
					DEFAULT: "var(--color-primary)",
					pressed: "var(--color-primary-pressed)",
					subtle: "var(--color-primary-subtle)",
					on: "var(--color-primary-on)",
				},
				highlight: {
					DEFAULT: "var(--color-highlight)",
					subtle: "var(--color-highlight-subtle)",
					on: "var(--color-highlight-on)",
				},
				feedback: {
					info: "var(--color-feedback-info)",
					"info-subtle": "var(--color-feedback-info-subtle)",
					success: "var(--color-feedback-success)",
					"success-subtle": "var(--color-feedback-success-subtle)",
					warning: "var(--color-feedback-warning)",
					"warning-subtle": "var(--color-feedback-warning-subtle)",
					error: "var(--color-feedback-error)",
					"error-subtle": "var(--color-feedback-error-subtle)",
				},
			},
			borderRadius: {
				sm: "8px",
				md: "12px",
				lg: "18px",
				xl: "26px",
				full: "9999px",
			},
			spacing: {
				0: "0px",
				1: "4px",
				2: "8px",
				3: "12px",
				4: "16px",
				5: "20px",
				6: "24px",
				8: "32px",
				10: "40px",
				12: "48px",
				"icon-sm": "16px",
				"icon-md": "20px",
				"icon-lg": "24px",
				"avatar-sm": "32px",
				"avatar-md": "40px",
				"avatar-lg": "56px",
				"control-sm": "32px",
				"control-md": "44px",
				"control-lg": "52px",
				"input-sm": "50px",
				"input-md": "56px",
				"input-lg": "64px",
				"screen-margin": "16px",
				"touch-target": "44px",
			},
			fontSize: {
				"large-title": [
					"34px",
					{
						lineHeight: "40px",
						fontWeight: "800",
						letterSpacing: "-0.8px",
					},
				],
				title1: [
					"28px",
					{
						lineHeight: "33px",
						fontWeight: "800",
						letterSpacing: "-0.6px",
					},
				],
				title2: [
					"22px",
					{
						lineHeight: "27px",
						fontWeight: "700",
						letterSpacing: "-0.4px",
					},
				],
				title3: [
					"20px",
					{
						lineHeight: "25px",
						fontWeight: "700",
						letterSpacing: "-0.3px",
					},
				],
				headline: [
					"17px",
					{
						lineHeight: "22px",
						fontWeight: "600",
						letterSpacing: "-0.2px",
					},
				],
				body: [
					"17px",
					{
						lineHeight: "23px",
						fontWeight: "400",
					},
				],
				callout: [
					"16px",
					{
						lineHeight: "21px",
						fontWeight: "400",
					},
				],
				subheadline: [
					"15px",
					{
						lineHeight: "20px",
						fontWeight: "400",
					},
				],
				footnote: [
					"13px",
					{
						lineHeight: "18px",
						fontWeight: "500",
					},
				],
				caption: [
					"12px",
					{
						lineHeight: "16px",
						fontWeight: "500",
					},
				],
			},
		},
	},
};

// The tokens of each component, copied by `axiom add` to ./components/<name>.css: every
// `--color-*` and `--radius-*` they declare becomes a Tailwind name.
const components = path.join(__dirname, "components");
if (fs.existsSync(components)) {
	for (const file of fs.readdirSync(components)) {
		if (!file.endsWith(".css")) continue;
		const css = fs.readFileSync(path.join(components, file), "utf8");
		for (const [, kind, name, value] of css.matchAll(
			/--(color|radius)-([\w-]+):\s*([^;]+);/g,
		)) {
			const group = kind === "color" ? "colors" : "borderRadius";
			preset.theme.extend[group][name] = value.trim();
		}
	}
}

module.exports = preset;
