import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { copyItems, type CopyOptions } from "../src/copy.ts";
import { resolveItems } from "../src/registry.ts";
import type { ProjectConfig, Registry } from "../src/types.ts";
import { config, tempDir, tempProject } from "./fixtures.ts";

/**
 * A small registry covering every placement rule: a flat layer (theme), a single file item (text),
 * a foldered item with a createOnly file per icon source (icon), a tokens file (button), and an
 * item with only a unistyles variant (fancy).
 */
const REGISTRY: Registry = {
	items: [
		{
			name: "theme",
			type: "foundations",
			files: [
				"theme/index.ts",
				{ path: "theme/components.ts", as: "components/index.ts" },
			],
		},
		{
			name: "text",
			type: "typography",
			files: ["text/text.tsx"],
			internalDependencies: ["theme"],
		},
		{
			name: "icon",
			type: "atoms",
			files: ["icon/icon.tsx", "icon/icon-types.ts"],
			iconSources: {
				custom: { files: [{ path: "icon/icons.tsx", createOnly: true }] },
			},
			internalDependencies: ["theme"],
		},
		{
			name: "button",
			type: "atoms",
			files: ["button/button.tsx", "button/button-tokens.ts"],
			tokens: "button/button-tokens.ts",
			dependencies: ["react-native-reanimated"],
			internalDependencies: ["icon", "text", "theme"],
		},
		{
			name: "fancy",
			type: "atoms",
			variants: { unistyles: { files: ["fancy/fancy.tsx"] } },
		},
	],
};

const SOURCES = {
	"registry.json": REGISTRY,
	"theme/index.ts": `export * from "@/theme/components";\n`,
	"theme/components.ts": `export const components = {};\n`,
	"text/text.tsx": `import { theme } from "@/theme";\nexport const Text = () => theme;\n`,
	"icon/icon.tsx": `import type { IconName } from "./icon-types";\nimport { icons } from "./icons";\nexport const Icon = (name: IconName) => icons[name];\n`,
	"icon/icon-types.ts": `export type IconName = string;\n`,
	"icon/icons.tsx": `export const icons = { close: 1 };\n`,
	"button/button.tsx": [
		`import { Icon } from "@/components/ui/icon";`,
		`import { Text } from "@/components/ui/text";`,
		`import { buttonTokens } from "@/components/ui/button-tokens";`,
		`const lazy = () => import("@/theme");`,
		`export const Button = () => [Icon, Text, buttonTokens, lazy];`,
		``,
	].join("\n"),
	"button/button-tokens.ts": `export const buttonTokens = {};\n`,
	"fancy/fancy.tsx": `export const Fancy = 1;\n`,
};

function setup(overrides: Partial<ProjectConfig> = {}) {
	return {
		registryRoot: tempDir(SOURCES),
		cwd: tempProject(),
		config: config({ icons: "custom", ...overrides }),
	};
}

function copy(
	{ registryRoot, cwd, config }: ReturnType<typeof setup>,
	names: string[],
	options: Partial<CopyOptions> = {},
) {
	return copyItems(resolveItems(REGISTRY, names), config, registryRoot, cwd, {
		requested: new Set(names),
		overwrite: "ask",
		...options,
	});
}

const read = (cwd: string, path: string) =>
	readFileSync(join(cwd, path), "utf8");

describe("copyItems", () => {
	test("places every file by its rule, and lists the npm dependencies", async () => {
		const project = setup();
		const result = await copy(project, ["button"]);

		expect(result.written.sort()).toEqual([
			"src/components/ui/button.tsx",
			"src/components/ui/icon/icon-types.ts",
			"src/components/ui/icon/icon.tsx",
			"src/components/ui/icon/icons.tsx",
			"src/components/ui/icon/index.ts",
			"src/components/ui/text.tsx",
			"src/theme/components/button.ts",
			"src/theme/components/index.ts",
			"src/theme/index.ts",
		]);
		expect(result.dependencies).toEqual(["react-native-reanimated"]);
	});

	test("rewrites imports to where each file now lives", async () => {
		const project = setup({
			aliases: {
				...config().aliases,
				components: "@/ui",
				theme: "@/design",
			},
		});
		await copy(project, ["button"]);

		expect(read(project.cwd, "src/ui/button.tsx")).toBe(
			[
				`import { Icon } from "@/ui/icon/icon";`,
				`import { Text } from "@/ui/text";`,
				`import { buttonTokens } from "@/design/components/button";`,
				`const lazy = () => import("@/design");`,
				`export const Button = () => [Icon, Text, buttonTokens, lazy];`,
				``,
			].join("\n"),
		);
		// Relative imports between the files of one item survive the move.
		expect(read(project.cwd, "src/ui/icon/icon.tsx")).toContain(
			`from "./icon-types";\nimport { icons } from "./icons";`,
		);
		// `as` files keep their subfolder, and the registry's address of it is rewritten.
		expect(read(project.cwd, "src/design/index.ts")).toBe(
			`export * from "@/design/components";\n`,
		);
	});

	test("generates a barrel per foldered item, the item's own file first", async () => {
		const project = setup();
		await copy(project, ["icon"]);
		expect(read(project.cwd, "src/components/ui/icon/index.ts")).toBe(
			`// Generated by axiom, so "@/components/ui/icon" resolves to this folder.\n` +
				`export * from "./icon";\nexport * from "./icon-types";\nexport * from "./icons";\n`,
		);
	});

	test("a second copy changes nothing", async () => {
		const project = setup();
		const first = await copy(project, ["button"]);
		const second = await copy(project, ["button"]);
		expect(second.written).toEqual([]);
		expect(second.unchanged.sort()).toEqual(first.written.sort());
	});

	describe("existing files that differ", () => {
		const edit = (cwd: string, path: string) =>
			writeFileSync(join(cwd, path), "// mine\n");

		test("never overwrites a createOnly file", async () => {
			const project = setup();
			await copy(project, ["icon"]);
			edit(project.cwd, "src/components/ui/icon/icons.tsx");

			const result = await copy(project, ["icon"], { overwrite: "force" });
			expect(result.kept).toEqual([
				{ path: "src/components/ui/icon/icons.tsx", reason: "owned" },
			]);
			expect(read(project.cwd, "src/components/ui/icon/icons.tsx")).toBe(
				"// mine\n",
			);
		});

		test("keeps dependencies, unless forced", async () => {
			const project = setup();
			await copy(project, ["button"]);
			edit(project.cwd, "src/components/ui/text.tsx");

			const kept = await copy(project, ["button"], { overwrite: "always" });
			expect(kept.kept).toEqual([
				{ path: "src/components/ui/text.tsx", reason: "dependency" },
			]);

			const forced = await copy(project, ["button"], { overwrite: "force" });
			expect(forced.written).toEqual(["src/components/ui/text.tsx"]);
		});

		test("asks for each requested file, and stops asking on none", async () => {
			const project = setup();
			await copy(project, ["button"]);
			edit(project.cwd, "src/components/ui/button.tsx");
			edit(project.cwd, "src/theme/components/button.ts");

			const asked: string[] = [];
			const result = await copy(project, ["button"], {
				confirm: async (path) => {
					asked.push(path);
					return "none";
				},
			});
			expect(asked).toHaveLength(1);
			expect(result.kept.map((file) => file.reason)).toEqual([
				"declined",
				"declined",
			]);

			const all = await copy(project, ["button"], {
				confirm: async () => "all",
			});
			expect(all.written).toHaveLength(2);
		});

		test("still asks about theme files with --overwrite", async () => {
			const project = setup();
			await copy(project, ["button"]);
			edit(project.cwd, "src/components/ui/button.tsx");
			edit(project.cwd, "src/theme/components/button.ts");

			const asked: string[] = [];
			const result = await copy(project, ["button"], {
				overwrite: "always",
				confirm: async (path) => {
					asked.push(path);
					return "no";
				},
			});
			expect(asked).toEqual(["src/theme/components/button.ts"]);
			expect(result.written).toEqual(["src/components/ui/button.tsx"]);
			expect(read(project.cwd, "src/theme/components/button.ts")).toBe(
				"// mine\n",
			);
		});

		test("keeps them when nobody can be asked", async () => {
			const project = setup();
			await copy(project, ["text"]);
			edit(project.cwd, "src/components/ui/text.tsx");
			const result = await copy(project, ["text"]);
			expect(result.kept).toEqual([
				{ path: "src/components/ui/text.tsx", reason: "declined" },
			]);
		});
	});

	describe("refusals", () => {
		test("an item without the project's variant", async () => {
			await expect(copy(setup(), ["fancy"])).rejects.toThrow(
				'"fancy" has no stylesheet variant yet.',
			);
			const unistyles = setup({ styling: "unistyles" });
			await copy(unistyles, ["fancy"]);
			expect(
				existsSync(join(unistyles.cwd, "src/components/ui/fancy.tsx")),
			).toBe(true);
		});

		test("an item needing an icon source the project hasn't set", async () => {
			await expect(
				copy(setup({ icons: undefined }), ["icon"]),
			).rejects.toThrow('"icon" needs an icon source');
			await expect(
				copy(setup({ icons: "expo-symbols" }), ["icon"]),
			).rejects.toThrow(
				`"icon" doesn't support the "expo-symbols" icon source.`,
			);
		});

		test("a relative import leaving the item", async () => {
			const project = setup();
			writeFileSync(
				join(project.registryRoot, "text/text.tsx"),
				`import { icons } from "../icon/icons";\n`,
			);
			await expect(copy(project, ["text"])).rejects.toThrow(
				`"../icon/icons" isn't a file of "text"`,
			);
		});

		test("leave the project untouched when one file fails", async () => {
			const project = setup();
			writeFileSync(
				join(project.registryRoot, "button/button-tokens.ts"),
				`import x from "./nope";\n`,
			);
			await expect(copy(project, ["button"])).rejects.toThrow();
			expect(existsSync(join(project.cwd, "src/components"))).toBe(false);
			expect(existsSync(join(project.cwd, "src/theme"))).toBe(false);
		});
	});
});
