// Writes the standalone form of every item that has one, per variant, so `typecheck.ts` checks them:
// .generated/standalone/<variant>/<item>.tsx, with a tsconfig.json that includes nothing else.
// A standalone file imports only npm packages, so it has to compile on its own.
//
//   bun scripts/standalone.ts
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { readRegistry } from "../../cli/src/registry.ts";
import { buildStandalone } from "../../cli/src/standalone.ts";
import { STYLINGS, isCssStyling, variantOf } from "../../cli/src/types.ts";

const root = join(import.meta.dirname, "..");
const registry = readRegistry(root);
const out = join(root, ".generated/standalone");

rmSync(out, { recursive: true, force: true });

let failed = false;
for (const variant of STYLINGS) {
	const dir = join(out, variant);
	let count = 0;

	for (const item of registry.items) {
		if (item.type === "foundations") continue;
		if (item.variants && !variantOf(item, variant)) continue;

		let result;
		try {
			result = buildStandalone(registry, root, item.name, {
				styling: variant,
				icons: "expo-symbols",
			});
		} catch (error) {
			// Items with no standalone form are refused on purpose; anything else is a bug.
			const message = (error as Error).message;
			if (message.includes("isn't available standalone")) continue;
			console.error(`${variant}/${item.name}: ${message}`);
			failed = true;
			continue;
		}

		mkdirSync(dir, { recursive: true });
		writeFileSync(join(dir, result.fileName), result.content);
		count++;
	}

	if (!count) continue;
	writeFileSync(
		join(dir, "tsconfig.json"),
		`// Generated by scripts/standalone.ts. Don't edit.\n${JSON.stringify(
			{
				extends: "../../../tsconfig.base.json",
				compilerOptions: { paths: {} },
				include: ["*.ts", "*.tsx"],
				// The `className` NativeWind and Uniwind add to React Native's props.
				...(isCssStyling(variant) && {
					files: [
						`../../../foundations/theme/tailwind/tailwind-env.${variant}.d.ts`,
					],
				}),
			},
			null,
			2,
		)}\n`,
	);
	console.log(`wrote .generated/standalone/${variant} (${count} items)`);
}

process.exit(failed ? 1 : 0);
