// Writes the theme of the NativeWind and Uniwind variants from the tokens, so `bg-primary`, `rounded-md` or
// `text-callout` mean the same values as in the other variants:
//
// - foundations/theme/tailwind/uniwind.css: Tailwind 4, for Uniwind;
// - foundations/theme/tailwind/nativewind.css and nativewind-preset.js: Tailwind 3, for NativeWind 4.
//
// Colors are CSS variables, set once for light and once for dark.
//
// It also writes the component tokens of the items that list `cssTokens` in registry.json, from
// their `<item>-tokens.ts`: `<item>-tokens.uniwind.css` and `<item>-tokens.nativewind.css`, where
// `solid.pressed.background` of `button` is `--color-button-solid-pressed`, so `bg-button-solid-pressed`.
//
// Run it after changing foundations/tokens/tokens.ts, foundations/theme/colors.ts or a tokens file.
//
// The files it imports read each other through aliases (`@/theme/tokens`). tsconfig.json only lists
// the config of each styling, so Bun is given one of them:
//
//   bun --tsconfig-override tsconfig.stylesheet.json scripts/theme-css.ts
import { readFileSync, writeFileSync as write } from "node:fs";
import { join } from "node:path";

import { plugin } from "bun";

import { format } from "../../cli/src/format.ts";

// Only the device knows the hairline width, and no class is generated from it.
plugin({
	name: "react-native-stub",
	setup(build) {
		build.module("react-native", () => ({
			exports: { StyleSheet: { hairlineWidth: 1 } },
			loader: "object",
		}));
	},
});

const root = join(import.meta.dirname, "..");

// Every file is formatted like the rest of the registry, so `bun run format` leaves it alone.
const pending: Promise<void>[] = [];
function writeFileSync(path: string, content: string) {
	pending.push(format(content, path).then((text) => write(path, text)));
}
const out = join(root, "foundations/theme/tailwind");

const { tokens } = (await import(
	join(root, "foundations/tokens/tokens.ts")
)) as typeof import("../foundations/tokens/tokens.ts");
type Colors = Record<string, Record<string, string>>;
// Not typed from the file: it imports the tokens through an alias this script's config doesn't map.
const { lightColors, darkColors } = (await import(
	join(root, "foundations/theme/colors.ts")
)) as { lightColors: Colors; darkColors: Colors };

const kebab = (name: string) =>
	name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const px = (value: number) => (value === 0 ? "0px" : `${value}px`);

/** `primary.default` is `primary`, `feedback.errorSubtle` is `feedback-error-subtle`. */
const colorName = (group: string, key: string) =>
	key === "default" ? kebab(group) : `${kebab(group)}-${kebab(key)}`;

const colorVars = (colors: Colors) =>
	Object.entries(colors).flatMap(([group, roles]) =>
		Object.entries(roles).map(
			([key, value]) => [`--color-${colorName(group, key)}`, value] as const,
		),
	);

const radii = Object.entries(tokens.radius).filter(([key]) => key !== "none");
const sizes = [
	...Object.entries(tokens.sizes).flatMap(([group, scale]) =>
		Object.entries(scale).map(
			([key, value]) => [`${group}-${key}`, value] as const,
		),
	),
	// The metrics that are lengths: `px-screen-margin`, `min-h-touch-target`.
	["screen-margin", tokens.metrics.screenMargin] as const,
	["touch-target", tokens.metrics.touchTarget] as const,
];
const typography = Object.entries(tokens.typography);

const HEADER = "Generated by scripts/theme-css.ts from the tokens. Don't edit.";
const block = (lines: (readonly [string, string])[], indent: string) =>
	lines.map(([name, value]) => `${indent}${name}: ${value};`).join("\n");

// Tailwind 4. `@theme` declares the utilities; the variants give each scheme its colors.
writeFileSync(
	join(out, "uniwind.css"),
	`/* ${HEADER} */
@theme {
${block(colorVars(lightColors), "\t")}

${block(
	radii.map(([key, value]) => [`--radius-${key}`, px(value)] as const),
	"\t",
)}

${block(
	sizes.map(([key, value]) => [`--spacing-${key}`, px(value)] as const),
	"\t",
)}

${typography
	.map(([name, style]) =>
		block(
			[
				[`--text-${kebab(name)}`, px(style.fontSize)],
				[`--text-${kebab(name)}--line-height`, px(style.lineHeight)],
				[`--text-${kebab(name)}--font-weight`, style.fontWeight],
				...("letterSpacing" in style
					? [
							[
								`--text-${kebab(name)}--letter-spacing`,
								px(style.letterSpacing),
							] as const,
						]
					: []),
			],
			"\t",
		),
	)
	.join("\n")}
}

@layer theme {
	:root {
		@variant light {
${block(colorVars(lightColors), "\t\t\t")}
		}
		@variant dark {
${block(colorVars(darkColors), "\t\t\t")}
		}
	}
}
`,
);

// Tailwind 3. The variables live in CSS, and the preset names them.
writeFileSync(
	join(out, "nativewind.css"),
	`/* ${HEADER} */
:root {
${block(colorVars(lightColors), "\t")}
}

@media (prefers-color-scheme: dark) {
	:root {
${block(colorVars(darkColors), "\t\t")}
	}
}
`,
);

const preset = {
	theme: {
		extend: {
			colors: Object.fromEntries(
				Object.entries(lightColors).map(([group, roles]) => [
					kebab(group),
					Object.fromEntries(
						Object.keys(roles).map((key) => [
							key === "default" ? "DEFAULT" : kebab(key),
							`var(--color-${colorName(group, key)})`,
						]),
					),
				]),
			),
			borderRadius: Object.fromEntries(
				radii.map(([key, value]) => [key, px(value)]),
			),
			// In pixels: NativeWind's `rem` is 14 on native, so Tailwind's own scale would be off.
			spacing: Object.fromEntries([
				...Object.entries(tokens.spacing).map(([key, value]) => [
					key,
					px(value),
				]),
				...sizes.map(([key, value]) => [key, px(value)]),
			]),
			fontSize: Object.fromEntries(
				typography.map(([name, style]) => [
					kebab(name),
					[
						px(style.fontSize),
						{
							lineHeight: px(style.lineHeight),
							fontWeight: style.fontWeight,
							...("letterSpacing" in style && {
								letterSpacing: px(style.letterSpacing),
							}),
						},
					],
				]),
			),
		},
	},
};
writeFileSync(
	join(out, "nativewind-preset.js"),
	`// ${HEADER}
/* global __dirname */
const fs = require("fs");
const path = require("path");

const preset = ${JSON.stringify(preset, null, "\t")};

// The tokens of each component, copied by \`axiom add\` to ./components/<name>.css: every
// \`--color-*\` and \`--radius-*\` they declare becomes a Tailwind name.
const components = path.join(__dirname, "components");
if (fs.existsSync(components)) {
	for (const file of fs.readdirSync(components)) {
		if (!file.endsWith(".css")) continue;
		const css = fs.readFileSync(path.join(components, file), "utf8");
		for (const [, kind, name, value] of css.matchAll(
			/--(color|radius)-([\\w-]+):\\s*([^;]+);/g,
		)) {
			const group = kind === "color" ? "colors" : "borderRadius";
			preset.theme.extend[group][name] = value.trim();
		}
	}
}

module.exports = preset;
`,
);

// Component tokens. The token functions are called with colors and radii that answer with the
// name of their variable, so a component token follows its theme token, in light and in dark.
const colorNames = Object.fromEntries(
	Object.entries(lightColors).map(([group, roles]) => [
		group,
		Object.fromEntries(
			Object.keys(roles).map((key) => [
				key,
				`var(--color-${colorName(group, key)})`,
			]),
		),
	]),
);
const radiusOf = new Map(
	Object.entries(tokens.radius).map(([key, value]) => [
		key === "none" ? "0px" : `var(--radius-${key})`,
		px(value),
	]),
);
const tokenNames = {
	...tokens,
	radius: Object.fromEntries(
		Object.keys(tokens.radius).map((key, i) => [
			key,
			[...radiusOf.keys()][i],
		]),
	),
};

const isObject = (value: unknown): value is Record<string, unknown> =>
	typeof value === "object" && value !== null;

/** The variables of one tokens object: `[name, value]`, the path to each value making its name. */
function variables(
	item: string,
	value: unknown,
	path: string[],
): [string, string][] {
	const name = (...parts: (string | false)[]) =>
		[item, ...parts.filter((part) => part && part !== "default")]
			.map((part) => kebab(part as string))
			.join("-");

	// `{ default, pressed, disabled }`: a state only lists what changes, the rest is `default`.
	if (
		isObject(value) &&
		isObject(value.default) &&
		!Object.values(value.default).some(isObject)
	) {
		const states = value as Record<string, Record<string, unknown>>;
		return Object.entries(states).flatMap(([state, own]) =>
			Object.entries({ ...states.default, ...own }).flatMap(
				([property, color]): [string, string][] => {
					if (color === undefined) return [];
					if (
						typeof color !== "string" ||
						// Nothing drawn is a color too: a state that clears a fill or a border.
						(color !== "transparent" && !color.startsWith("var(--color-"))
					)
						throw new Error(
							`${item}: ${[...path, state, property].join(".")} isn't a theme color.`,
						);
					return [
						[
							// The background names the surface itself: `bg-button-solid`.
							`--color-${name(...path, property !== "background" && property, state)}`,
							color,
						],
					];
				},
			),
		);
	}
	if (isObject(value))
		return Object.entries(value).flatMap(([key, child]) =>
			variables(item, child, [...path, key]),
		);
	if (path.at(-1) === "radius" && radiusOf.has(value as string))
		return [[`--radius-${name(...path.slice(0, -1))}`, value as string]];
	throw new Error(
		`${item}: ${path.join(".")} has no CSS form yet. scripts/theme-css.ts knows colors and \`radius\`.`,
	);
}

const registry = JSON.parse(
	readFileSync(join(root, "registry.json"), "utf8"),
) as {
	items: {
		name: string;
		tokens?: string;
		cssTokens?: { uniwind?: string; nativewind?: string };
	}[];
};
const camelCase = (name: string) =>
	name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());

for (const item of registry.items) {
	if (!item.cssTokens || !item.tokens) continue;
	const module = (await import(join(root, item.tokens))) as Record<
		string,
		(colors: unknown, tokens: unknown) => unknown
	>;
	const all = variables(
		item.name,
		module[`${camelCase(item.name)}Tokens`](colorNames, tokenNames),
		[],
	);
	const header = `/* Generated by scripts/theme-css.ts from ${item.tokens.split("/").at(-1)}. Edit it in your project to restyle ${item.name}. */`;

	// Tailwind 4. `inline` writes the theme's variable into the utility: `bg-button-solid` is
	// \`background-color: var(--color-primary)\`, and follows the scheme like `bg-primary` does.
	if (item.cssTokens.uniwind)
		writeFileSync(
			join(root, item.cssTokens.uniwind),
			`${header}\n@theme inline {\n${block(all, "\t")}\n}\n`,
		);
	// Tailwind 3. Read by theme/nativewind-preset.js, which names each variable for Tailwind.
	if (item.cssTokens.nativewind)
		writeFileSync(
			join(root, item.cssTokens.nativewind),
			`${header}\n:root {\n${block(
				all.map(
					([name, value]) => [name, radiusOf.get(value) ?? value] as const,
				),
				"\t",
			)}\n}\n`,
		);
	console.log(
		`wrote the CSS tokens of ${item.name} (${all.length} variables)`,
	);
}

await Promise.all(pending);
console.log(
	"wrote foundations/theme/tailwind/{uniwind.css,nativewind.css,nativewind-preset.js}",
);
