// Writes the tsconfig files of the registry, so editors and tsc resolve alias imports in place.
// Each alias import (`@/components/ui/text`) is mapped to the registry file it will be copied from,
// following the same rules as the CLI: the item folder and the variant folder are flattened.
//
// `stylesheet` goes to tsconfig.json, the file editors read. Other variants get tsconfig.<variant>.json.
//
// The theme's components.ts is a template that `axiom add` fills. `@/theme/components` points to
// .generated/components.ts instead, with the tokens of every registry item registered.
//
//   bun scripts/tsconfig.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative } from "node:path";

import { readRegistry } from "../../cli/src/registry.ts";
import { registerTokens, tokenEntries } from "../../cli/src/tokens.ts";
import {
	ALIAS_OF,
	DEFAULT_ALIASES,
	VARIANTS,
	type RegistryFile,
} from "../../cli/src/types.ts";

const root = join(import.meta.dirname, "..");
const registry = readRegistry(root);

const pathOf = (file: RegistryFile) =>
	typeof file === "string" ? file : file.path;

const COMPONENTS_TEMPLATE = "foundations/theme/components/index.ts";
const GENERATED_DIR = ".generated/components";
const GENERATED_COMPONENTS = `${GENERATED_DIR}/index.ts`;

// The theme's components/index.ts imports each tokens file as `./<component>`, the name it takes
// once copied. Relative imports can't be remapped by tsconfig paths, so the folder is mirrored
// here: one stub per component, re-exporting the registry file it will be copied from.
mkdirSync(join(root, GENERATED_DIR), { recursive: true });
writeFileSync(
	join(root, GENERATED_COMPONENTS),
	`// Generated by scripts/tsconfig.ts: ${COMPONENTS_TEMPLATE} with every registry item's tokens. Don't edit.\n` +
		registerTokens(
			readFileSync(join(root, COMPONENTS_TEMPLATE), "utf8"),
			tokenEntries(registry.items, DEFAULT_ALIASES),
		),
);
writeFileSync(
	join(root, GENERATED_DIR, "states.ts"),
	`// Generated by scripts/tsconfig.ts. Don't edit.\nexport * from "../../foundations/theme/components/states";\n`,
);
for (const item of registry.items) {
	if (!item.tokens) continue;
	const to = relative(
		join(root, GENERATED_DIR),
		join(root, item.tokens.slice(0, -extname(item.tokens).length)),
	);
	writeFileSync(
		join(root, GENERATED_DIR, `${item.name}.ts`),
		`// Generated by scripts/tsconfig.ts. Don't edit.\nexport * from "${to}";\n`,
	);
}

/** The folder an item owns, shared by every file it can copy: the shallowest of their directories. */
function itemRoot(item: (typeof registry.items)[number]): string | undefined {
	const files = [
		...(item.files ?? []),
		...Object.values(item.variants ?? {}).flatMap((set) => set.files ?? []),
		...Object.values(item.iconSources ?? {}).flatMap(
			(set) => set.files ?? [],
		),
		...Object.values(item.navigationSources ?? {}).flatMap(
			(set) => set.files ?? [],
		),
	];
	const dirs = files.map((file) => dirname(pathOf(file)));
	return dirs.sort((a, b) => a.length - b.length)[0];
}

for (const variant of VARIANTS) {
	const paths: Record<string, string[]> = {};
	const covered = new Set<string>();
	const uncovered = new Set<string>();
	let count = 0;

	for (const item of registry.items) {
		const root = itemRoot(item);
		if (item.variants && !item.variants[variant]) {
			if (root) uncovered.add(root);
			continue;
		}
		if (root) covered.add(root);

		const alias = DEFAULT_ALIASES[ALIAS_OF[item.type]];
		// Aliases point to the first icon and navigation source; the others are still typechecked through the include globs.
		const [iconSource] = Object.values(item.iconSources ?? {});
		const [navigationSource] = Object.values(item.navigationSources ?? {});
		const files = [
			...(item.files ?? []),
			...(item.variants?.[variant]?.files ?? []),
			...(iconSource?.files ?? []),
			...(navigationSource?.files ?? []),
		];
		for (const file of files) {
			const path = pathOf(file);
			count++;

			// A tokens file is addressed through the theme, and only by the generated aggregator.
			if (item.tokens === path) continue;

			// `as` keeps a subfolder inside the alias; otherwise the file name is the address.
			const as = typeof file === "string" ? undefined : file.as;
			const within = as
				? as.slice(0, -extname(as).length)
				: basename(path, extname(path));
			// `index` files are imported through the folder itself (`@/theme`, `@/theme/components`).
			const key = within.replace(/(^|\/)index$/, "");
			paths[key ? `${alias}/${key}` : alias] = [`./${path}`];
		}
	}

	if (!registry.items.some((item) => item.variants?.[variant])) continue;
	// The theme's components/index.ts is a template that `axiom add` fills; the generated one has
	// every registry item's tokens registered.
	paths["@/theme/components"] = [`./${GENERATED_COMPONENTS}`];

	// Every file of the variant, listed in registry.json or not, so editors never fall back to a config without paths.
	const otherVariants = VARIANTS.filter((other) => other !== variant).map(
		(other) => `**/${other}/**`,
	);
	// An item that doesn't offer the variant yet isn't part of it: its shared files import aliases
	// this config doesn't map, so the whole folder stays out.
	const missing = [...uncovered]
		.filter(
			(dir) =>
				![...covered].some(
					(other) => other === dir || other.startsWith(`${dir}/`),
				),
		)
		.sort()
		.map((dir) => `${dir}/**`);
	const tsconfig = {
		extends: "./tsconfig.base.json",
		compilerOptions: { paths },
		include: ["**/*.ts", "**/*.tsx"],
		exclude: ["node_modules", "scripts", ...otherVariants, ...missing],
	};

	const file =
		variant === "stylesheet" ? "tsconfig.json" : `tsconfig.${variant}.json`;
	writeFileSync(
		join(root, file),
		`// Generated by scripts/tsconfig.ts from registry.json. Don't edit.\n${JSON.stringify(tsconfig, null, 2)}\n`,
	);
	console.log(`wrote ${file} (${count} files mapped)`);
}
