// Writes the tsconfig files of the registry, so editors and tsc resolve alias imports in place.
// Each alias import (`@/components/ui/text`) is mapped to the registry file it will be copied from,
// following the same rules as the CLI: the item folder and the variant folder are flattened.
//
// `stylesheet` goes to tsconfig.json, the file editors read. Other variants get tsconfig.<variant>.json.
//
// The theme's components.ts is a template that `axiom add` fills. `@/theme/components` points to
// .generated/components.ts instead, with the tokens of every registry item registered.
//
//   bun scripts/tsconfig.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';

import { readRegistry } from '../../cli/src/registry.ts';
import { registerTokens, tokenEntries } from '../../cli/src/tokens.ts';
import { ALIAS_OF, DEFAULT_ALIASES, type RegistryFile, type Variant } from '../../cli/src/types.ts';

const root = join(import.meta.dirname, '..');
const registry = readRegistry(root);
const VARIANTS: Variant[] = ['stylesheet', 'unistyles', 'tailwind'];

const pathOf = (file: RegistryFile) => (typeof file === 'string' ? file : file.path);

const COMPONENTS_TEMPLATE = 'foundations/theme/components.ts';
const GENERATED_COMPONENTS = '.generated/components.ts';

mkdirSync(join(root, '.generated'), { recursive: true });
writeFileSync(
  join(root, GENERATED_COMPONENTS),
  `// Generated by scripts/tsconfig.ts: ${COMPONENTS_TEMPLATE} with every registry item's tokens. Don't edit.\n` +
    registerTokens(readFileSync(join(root, COMPONENTS_TEMPLATE), 'utf8'), tokenEntries(registry.items, DEFAULT_ALIASES)),
);

for (const variant of VARIANTS) {
  const paths: Record<string, string[]> = {};
  let count = 0;

  for (const item of registry.items) {
    if (item.variants && !item.variants[variant]) continue;

    const alias = DEFAULT_ALIASES[ALIAS_OF[item.type]];
    // Aliases point to the first icon source; the others are still typechecked through the include globs.
    const [iconSource] = Object.values(item.iconSources ?? {});
    for (const file of [...(item.files ?? []), ...(item.variants?.[variant]?.files ?? []), ...(iconSource?.files ?? [])]) {
      const path = pathOf(file);
      count++;

      const name = basename(path, extname(path));
      // `index` files are imported through the alias itself (`@/theme`).
      paths[name === 'index' ? alias : `${alias}/${name}`] = [`./${path}`];
    }
  }

  if (!registry.items.some((item) => item.variants?.[variant])) continue;
  paths['@/theme/components'] = [`./${GENERATED_COMPONENTS}`];

  // Every file of the variant, listed in registry.json or not, so editors never fall back to a config without paths.
  const otherVariants = VARIANTS.filter((other) => other !== variant).map((other) => `**/${other}/**`);
  const tsconfig = {
    extends: './tsconfig.base.json',
    compilerOptions: { paths },
    include: ['**/*.ts', '**/*.tsx'],
    exclude: ['node_modules', 'scripts', ...otherVariants],
  };

  const file = variant === 'stylesheet' ? 'tsconfig.json' : `tsconfig.${variant}.json`;
  writeFileSync(
    join(root, file),
    `// Generated by scripts/tsconfig.ts from registry.json. Don't edit.\n${JSON.stringify(tsconfig, null, 2)}\n`,
  );
  console.log(`wrote ${file} (${count} files mapped)`);
}
